import './globals.css'

import type { Metadata } from 'next'

import DatadogInit from '@/lib/datadog'

import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="pt-BR">
      <body>
        <Providers>
          <DatadogInit />
          {children}
        </Providers>
      </body>
    </html>
  )
}
